[project]
name = "dart-forecasting"
r_version = "4.5"

repositories = [
  { alias = "P3M", url = "https://packagemanager.posit.co/cran/latest" },
  { alias = "CRAN", url = "https://cloud.r-project.org" },
]

dependencies = [
  "targets",
  "autometric",
  "crew",
  "tidyverse",
  "qs2",
  ## tar_watch() deps
  "DT",
  "gt",
  "markdown",
  "shiny",
  "shinybusy",
  "shinyWidgets",
  "visNetwork",
  "parallelly",
  ## ----------------
  "toml",
  "stars",
  "ncmeta",
  "ISOweek",
  { name = "mlr3forecast", git = "https://github.com/mlr-org/mlr3forecast.git", commit = "0b6cef9525e9fc0cb0430e52eb95e413edc70fee" },
  "mlr3learners",
  "ranger",
  { name = "AdaptiveConformal", git = "https://github.com/herbps10/AdaptiveConformal.git", commit = "7c45149e676f37f3cbb759bcf92292d5bfe745c8" },
  { name = "opera", git = "https://github.com/Dralliag/opera.git", commit = "24070db124c14df022c9356a3b517599ffd95148" },
  "mlr3",
]
