[data.paths]
incidence = "data/incidence/incidence_2000_2026.csv"
weather = "data/weather"
mlr3_objs = "data/mlr3_objs"

[forecast]
region = "VNM"
admin_level = 1
max_horizon = 12
learner_id = "regr.ranger"

[forecast.met_data]
load_met_data = true
load_era = false
load_wrf_ds = true
